# Generated by Django 5.2.13 on 2026-05-01 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Panel3XUI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("base_url", models.URLField()),
                ("username", models.CharField(max_length=120)),
                ("password", models.CharField(max_length=120)),
                (
                    "inbound_id",
                    models.IntegerField(
                        help_text="3x-ui inbound id used for new clients"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_fa", models.CharField(max_length=100)),
                ("name_en", models.CharField(max_length=100)),
                ("duration_days", models.PositiveIntegerField()),
                ("traffic_gb", models.PositiveIntegerField()),
                ("price", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("telegram_user_id", models.BigIntegerField(db_index=True)),
                ("email", models.CharField(max_length=120, unique=True)),
                ("config_link", models.TextField(blank=True)),
                ("status", models.CharField(default="active", max_length=20)),
                ("expire_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "panel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.panel3xui"
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.plan"
                    ),
                ),
            ],
        ),
    ]
