# Generated by Django 5.2.1 on 2026-05-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_paymentsettings_paymentreceipt"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(default="default", max_length=30, unique=True),
                ),
                ("telegram_bot_token", models.CharField(blank=True, max_length=255)),
                (
                    "service_api_name",
                    models.CharField(default="bot-seller-api", max_length=120),
                ),
                (
                    "service_bot_name",
                    models.CharField(default="bot-seller-bot", max_length=120),
                ),
                ("allow_admin_restart", models.BooleanField(default=False)),
            ],
        ),
    ]
